### ISSUE TITLE
Instructions for Stickermule need to be updated

### ISSUE THREAD

**Issue by angela-li** [rladies/starter-kit#145] opened 2019-08-27 16:21 UTC
From recent experience, you can now simply upload the [hex-logo-with-text.png](https://github.com/rladies/starter-kit/blob/master/stickers/hex-logo-with-text.png) file, and they'll process it correctly (aka they don't need a bleed anymore). It would be great to revise the sticker instructions to reflect this!

**Comment by cvitolo** [comment] 2019-10-12 07:21
Hi @angela-li , thanks for the suggestion. Can I assign you to this issue?

**Comment by maelle** [comment] 2021-03-11 08:21
Duplicate of https://github.com/rladies/rladiesguide/issues/13

**Closed by maelle** 2021-03-11 08:21 UTC
